### ISSUE TITLE
File e_sqlite3.dll not included when publishing for runtime win-x64

### ISSUE THREAD

**Issue by nwoolls** [ericsink/SQLitePCL.raw#184]
Given the following project:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SQLitePCLRaw.bundle_green" Version="1.1.9" />
  </ItemGroup>
</Project>
```

Running the following publish command:

```
dotnet publish -f netcoreapp2.0 -c release -r win7-x64
```

Yields a publish folder with the `e_sqlite3.dll` file:

```
> ls bin/release/netcoreapp2.0/win7-x64/publish/e_sqlite3.dll
bin/release/netcoreapp2.0/win7-x64/publish/e_sqlite3.dll
```

However, running the following publish command (runtime is **win-x64** rather than **win7-x64**):

```
dotnet publish -f netcoreapp2.0 -c release -r win-x64
```

Results in a publish folder that is missing `e_sqlite3.dll`:

```
> ls bin/release/netcoreapp2.0/win-x64/publish/e_sqlite3.dll
ls: bin/release/netcoreapp2.0/win-x64/publish/e_sqlite3.dll: No such file or directory
```

This results in an error at runtime: `System.DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`.

**Comment by nwoolls** [comment]
Some official docs on the topic:

* https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
* https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/#user-content-much-easier-to-target-linux-as-a-single-operating-system

> Similar improvements have been made for Windows and macOS. You can now publish for the following “runtimes”.
> 
> * linux-x64, linux-arm
> * win-x64, win-x86
> * osx-x64


And discussion of how these changed WRT .NET Core 2.0 (vs 1.0):

* https://stackoverflow.com/questions/41766002/what-does-the-win-any-runtime-mean-in-net-core/41863501#41863501

**Comment by ericsink** [comment]
Hmmm.  Thanks for the links.  But this information (surprisingly) doesn't clarify things.

Most of the information seems to focus on what RID you can provide to "dotnet publish", as opposed to what the RID folder in the nuget package should be named.

I'm putting native files in `runtimes\win7-x64\native`, because in general, I get the impression that the name of the RID folder in the nupkg should be more specific.  Based on the compatibility graph information, I would expect that publish for `win-x64` should work with this approach, but it apparently does not.

Looking at other packages which bundle a native library, I see them using RID folders like win7-x64, just as I am.  I haven't found an example of someone using `win-x64` as a RID folder in the package.

I am not saying that I don't want `publish win-x64` to work.  I do.  I'm just saying that I am not sure about the correct way to achieve that.  I suppose I could just change the name of that folder to `win-x64` and see if it works.

**Comment by bricelam** [comment]
Here are the rules: https://github.com/dotnet/corefx/blob/v2.0.3/pkg/Microsoft.NETCore.Platforms/runtime.json

Notice `win-*` and `win7-*` aren't actually equivalent. `win` is compatible with `win7`, but `win7` isn't compatible with `win`. So if I publish for `win-x64`, it won't look for assets under `win7-x64`.

For package authors, this means native assets probably shouldn't be under `win7-*`. They should use `win-*` instead.

For users publishing, this means they should use the exact RID they're publishing for. Use `win10-x64` if it will run on Windows 10, not `win-x64`. This insures the most correct assets are published.

**Comment by ericsink** [comment]
@bricelam Excellent.

So for a package author, a single native code asset which is compatible with Windows 7, 8 or 10 would go under `win-`.  (This is my situation.)

But if a package author had a native code asset which is specifically for Windows 7, they would use `win7-`, and so on.

And if they had separate builds for Windows 7, 8 and 10, they would put each one under the corresponding specific RID.

Thanks!

**Comment by jwdavidson** [comment]
In addition when I tried to rename the provided SQLitePCL.Raw.provider.e_sqlite3.dll to just e_sqlite3.dll it did correct the issue with the dll not found, but introduced a new error about libversion information not being found.  See @smitpatel above for original report

**Comment by jwdavidson** [comment]
The package with the fix does not show as an available update, when using Microsoft.AspNetCore.All

It looks like the shortcut may create as many issues as it solves. I was able to update a 3 project solution from Core 1.0 to Core 2.0 in about 3 hours, but spent another 10 trying to get those projects work in production due to this single issue.

**Comment by ericsink** [comment]
I'm not sure what "shortcut" you mean.  Maybe "tried to rename the provided SQLitePCL.Raw.provider.e_sqlite3.dll to just e_sqlite3.dll".  If so, yeah, you should not do that.  :-)

Anwyay, as you discovered, the problem you found was fixed in 1.1.10.

**Comment by jwdavidson** [comment]
The package Microsoft.AspNetCore.All is a shortcut, rather than providing the names of all the individual packages required for ASPNet Core.

**Comment by ericsink** [comment]
Ah, yes.  That makes sense.

**Comment by ilbassodigenova** [comment]
Still have the problem. One (or two) out of three times i debug with VS2017, i got this
`DllNotFoundException: Unable to load DLL 'e_sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

The project is in .net Framework 4.8
There is a walkaround: When cleaning, changing architecture (move from AnyCpu to x64 and viceversa) everything goes fine again. For once or twice.

**Comment by win7user10** [comment]
I had the same bug in a project as @ilbassodigenova described. The project has been successfully run once and then I got `DllNotFoundException`. In my case, my project2 has a reference to a project1 that has a link to `Microsoft.EntityFrameworkCore.Sqlite 2.1.14`. When I added the same library link to project2 it started work.
